### ISSUE TITLE
UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.BitbucketAuthenticationToken

### ISSUE THREAD

**Issue by shuraa** [mallowlabs/bitbucket-oauth-plugin#8]
Hi!

After upgrading Jenkins to 2.3 I faced with the issue:
`FATAL: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.BitbucketAuthenticationToken
java.lang.ClassCastException: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.BitbucketAuthenticationToken
	at org.jenkinsci.plugins.BitbucketSecurityRealm.loadUserByUsername(BitbucketSecurityRealm.java:162)
	at hudson.model.User$UserIDCanonicalIdResolver.resolveCanonicalId(User.java:1048)
	at hudson.model.User.get(User.java:394)
	at hudson.model.User.get(User.java:363)
	at hudson.plugins.git.GitChangeSet.findOrCreateUser(GitChangeSet.java:374)
	at hudson.plugins.git.GitChangeSet.getAuthor(GitChangeSet.java:435)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:350)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:672)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)`

Jenkins 2.3 running on Ubuntu 14.04 TLS under OpenJDK 1.7.

**Comment by mallowlabs** [comment]
I released version 0.5.
Please try it.

**Comment by shuraa** [comment]
@mallowlabs , thank you! The issue is gone.
